@host = https://a3gzm9fm65.execute-api.eu-west-1.amazonaws.com/data
###

GET {{host}} 
Content-Type:  application/json
Authorization: Bearer eyJraWQiOiI1TTQwZDFtSlNMM0g4NWtCc1BUdWp6VGd4eEVuaWQ4OFJjbHBKbjJzbFdZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI1ZWJhM2QwMC0zNWNkLTRmOGEtYWNmYy1lZDA4Y2M1N2ZkMTciLCJhdWQiOiI3MGpyaGx2c3M4aHJzbHBrbXNkbTY3bG8wZyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6ImEyY2QwOWQ5LTQ3ZDQtNDI2Zi04MTlmLTQ4YjYwZWJkZjM4ZiIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjcxMjA5NDgzLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9MM1NMTlRHcHoiLCJjb2duaXRvOnVzZXJuYW1lIjoiNWViYTNkMDAtMzVjZC00ZjhhLWFjZmMtZWQwOGNjNTdmZDE3IiwiZXhwIjoxNjcxMjEzMDgzLCJpYXQiOjE2NzEyMDk0ODMsImVtYWlsIjoiYXNzaWdubWVudF91c2VyXzFAb3B1cy5ubCJ9.c0Jfl8KkrF3iU8-jsCtEYROK2Ilb4m7REsFPhdZyv7x8myigff490Wn9jVhbSMLvu5Q6EqWte9JK0xSnAQen7zVpQ8C2v4xhQ4v2rFcqCPJIlYrRFORsQCJAcbuhOuPUHiKwz_sYxSo2LqTVgYa2pfzu2rgxPPBhVY3PQQFBRADUhkCx104vicsArJyNDb8Yjzq3xRHN8HebvlVRogBtMVpaOGPIAiyIhOYmDEwttCVDCb5jyKf0Ywni6D5RJLWDsqsS2LSdulQfAf-aIKmx3uNktygAhwluF1UblD6zi7waf-V8GkCqj6RQjZDXVmlKTudV6ldEdwITcWymTgUTwQ